# Generated by Django 5.0.2 on 2024-02-14 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('present', 'Present'), ('permanent', 'Permanent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='cnic',
            field=models.BigIntegerField(max_length=13),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('nonbinary', 'Nonbinary')], max_length=10),
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('current', 'Current'), ('alternative', 'Alternative')], max_length=50)),
                ('contact', models.BigIntegerField(max_length=11)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_degree', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=2)),
                ('year_of_passing', models.IntegerField(max_length=4)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('home', 'Home'), ('office', 'Office')], max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Other_Professional_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_job', models.CharField(max_length=50)),
                ('organization_name', models.CharField(max_length=50)),
                ('job_period_from', models.DateField()),
                ('job_period_to', models.DateField()),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Professional_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_description', models.CharField(max_length=50)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('contact_no', models.BigIntegerField(max_length=11)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Religious_Or_Political_Af',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('name_of_party', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_taught', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('teaching_period_from', models.DateField()),
                ('teaching_period_to', models.DateField()),
                ('age_group_taught', models.IntegerField(max_length=2)),
                ('references_name', models.CharField(max_length=50)),
                ('references_contact_no', models.BigIntegerField(max_length=11)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
    ]
