# Generated by Django 5.0.2 on 2024-02-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMAdmin', '0002_alter_address_address_type_alter_personalinfo_cnic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='cnicback',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='cnicfront',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-binary')], max_length=10),
        ),
    ]
