# Generated by Django 5.0.2 on 2024-02-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMAdmin', '0003_personalinfo_cnicback_personalinfo_cnicfront_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='cnicback',
            new_name='cnicBack',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='cnicfront',
            new_name='cnicFront',
        ),
    ]
