# Generated by Django 5.0.1 on 2024-02-15 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMAdmin', '0004_rename_cnicback_personalinfo_cnicback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_employee', models.CharField(max_length=50, null=True)),
                ('position', models.CharField(choices=[('intern', 'Intern'), ('regular', 'Regular')], max_length=50)),
                ('core_area', models.CharField(choices=[('webdeveloper', 'Web Developer'), ('graphicdesigner', 'Graphic Designer'), ('seoengineer', 'SEO Engineer'), ('softwaredeveloper', 'Software Developer')], max_length=50)),
                ('reporting_supervisor', models.CharField(choices=[('alishoaibzaidi', 'Ali Shoaib Zaidi'), ('zaynalinaqvi', 'Zayn Ali Naqvi'), ('syedmujtaba', 'Syed Mujtaba'), ('aijazmahdavi', 'Aijaz Mahdavi')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='date_of_joining',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contactnumber',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='EMAdmin.employeesalary')),
            ],
        ),
    ]
