# Generated by Django 5.0.1 on 2024-02-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMAdmin', '0005_employeesalary_occupation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='date_of_joining',
        ),
        migrations.DeleteModel(
            name='EmployeeSalary',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
